### EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

##### ---------------------------------------------------------------------------------------------------------------------------

##### Name: ARAO, Angeline Jeannah E.
##### Year & Section: 2ECE-A

##### ---------------------------------------------------------------------------------------------------------------------------

#### NORMALIZATION PROBLEM

In [31]:
# Access the Numpy library
import numpy as np

# Create a random 5x5 ndarray and store it to variable X
X = np.random.random((5,5))

# Normalize X by utilizing .mean() and .std()
X_normalized = (X - X.mean()) / X.std()

# Save the normalized ndarray as 'X_normalized.npy'
np.save('X_normalized.npy', X_normalized)

# Result
print("X:\n", X, "\n\nMean:", X.mean(), "\n\nStandard Deviation:", X.std(), "\n\nNormalized 'X' Values:\n", np.load('X_normalized.npy'))

X:
 [[0.89576043 0.56682623 0.83266443 0.84418651 0.23891865]
 [0.63208289 0.01731075 0.76025075 0.40044869 0.44908465]
 [0.44161163 0.82336511 0.14203722 0.29711877 0.82812537]
 [0.38815146 0.3619528  0.1269165  0.24736121 0.15896497]
 [0.13460903 0.28715936 0.28861868 0.81265431 0.43149076]] 

Mean: 0.4563068464459606 

Standard Deviation: 0.26855871479172577 

Normalized 'X' Values:
 [[ 1.6363408   0.41152781  1.40139777  1.44430117 -0.80946247]
 [ 0.65451626 -1.6346373   1.13175959 -0.20799233 -0.02689242]
 [-0.05471882  1.36677101 -1.17020826 -0.59274964  1.38449622]
 [-0.25378206 -0.35133489 -1.22651149 -0.77802592 -1.10717643]
 [-1.19786773 -0.62983427 -0.62440038  1.32688847 -0.0924047 ]]


#### DIVISIBLE BY 3 PROBLEM

In [57]:
# Access the Numpy library
import numpy as np

# Create a 10x10 ndarray with the squares of the first 100 positive integers
A = np.array(range(1,101)) ** 2

# Reshape array to 10x10
A = A.reshape (10, 10)

# Determine all elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save the values from div_by_3 as ".npy"
np.save('div_by_3.npy', div_by_3)

# Result
print ("Squares of the First 100 Positive Integers:\n", A, "\n\n\nThe Numbers that are divisible by 3:\n", div_by_3)

Squares of the First 100 Positive Integers:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 


The Numbers that are divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
